# Generated by Django 4.0.2 on 2022-02-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_profile_city_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='city',
            new_name='city_id',
        ),
    ]
