# Generated by Django 4.0.2 on 2022-02-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_city_post_city_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='city_id',
            new_name='cities',
        ),
    ]
